### ISSUE TITLE
docs: Create CODE_OF_CONDUCT and CONTRIBUTING.md

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Aryan-Srivastava/College_Post#10]
To help newbies better understand about contribution and open source.

**Comment by the-amazing-atharva** [comment]
Hi I would like to create the above files!!

Do assign me

**Comment by Aryan-Srivastava** [comment]
@the-amazing-atharva Great go ahead

**Comment by the-amazing-atharva** [comment]
Thanks for the reply

Working on it now!!!

**Comment by Aryan-Srivastava** [comment]
Hey, @the-amazing-atharva is it done because it's been a week since then? If yes, please commit.

**Comment by the-amazing-atharva** [comment]
Done bro, also have raised a PR for that
