### ISSUE TITLE
About page is not completely mobile responsive.

### ISSUE THREAD

**Issue by Nikhil7174** [Aryan-Srivastava/College_Post#21]
![Screenshot (167)](https://user-images.githubusercontent.com/40711348/218982340-dfe489f1-6fbd-47b8-b22e-cc9fbfaa556f.png)
![Screenshot (168)](https://user-images.githubusercontent.com/40711348/218982344-6f912e10-62ab-42f7-8274-f8c2c000efaa.png)

**Comment by Nikhil7174** [comment]
@Aryan-Srivastava Can i work on this issue?

**Comment by Aryan-Srivastava** [comment]
yes, but it'll be considered as an extension of the #19 and not as individual issue because you was working on the issue #4 .
