### ISSUE TITLE
Feat: Mobile responsive

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Aryan-Srivastava/College_Post#4]
Website is not currently fully mobile responsive.

**Comment by Nikhil7174** [comment]
Please assign me this issue.

**Comment by Nikhil7174** [comment]
I have got 3 easy and 2 difficult pr merged but still pwoc leaderboard is
showing 14 pts instead of 18 pts. Please have a look into this issue and
excuse me for this silly request. My account name is Nikhil7174 .

**Comment by Aryan-Srivastava** [comment]
You should talk with the moderators on discord, they'll help you, I can't do anything in this matter
