### ISSUE TITLE
Feat: Dark Mode

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Aryan-Srivastava/College_Post#5]
Try to enable dark mode for the website.

**Comment by kavyarishi19** [comment]
assign me

**Comment by Aryan-Srivastava** [comment]
assigned! ✌️ good luck

**Comment by Aryan-Srivastava** [comment]
@kavyarishi19 any update regarding this?

**Comment by Nikhil7174** [comment]
@Aryan-Srivastava If this issue is still open can i work on it?

**Comment by Aryan-Srivastava** [comment]
@kavyarishi19 Any update with the issue if you're working on this please reply

**Comment by Aryan-Srivastava** [comment]
@Nikhil7174 you can work on this, go ahead
